apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $app_name
    in-service: "true"
  name: $app_name
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: $app_name
      in-service: "true"
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: $app_name
        in-service: "true"
    spec:
      containers:
      - env:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access-key-id
              name: aws-access-secret
        - name: S3_ACCESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: access-key-secret
              name: aws-access-secret
        envFrom:
        - configMapRef:
            name: edd-estimated-date-configs
        image: 812436859307.dkr.ecr.us-west-2.amazonaws.com/edd/tcp_edd_estimated_date:$IMAGE_TAG
        imagePullPolicy: IfNotPresent
        name: $app_name
        ports:
        - containerPort: 2020
          name: app-port
          protocol: TCP
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health
            port: 2020
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /actuator/health
            port: 2020
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1500m"
            memory: 2560Mi
          requests:
            cpu: "1"
            memory: 2560Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
